# Generated by Django 4.1.3 on 2022-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shops_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
