# Generated by Django 4.1.7 on 2023-02-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='shops',
            name='currency',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
