# Generated by Django 4.1.7 on 2023-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shops_country_shops_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='site_date',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Site original date'),
        ),
    ]
