# Generated by Django 4.1.7 on 2023-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shops_site_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='site_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Site original date'),
        ),
    ]
