# Generated by Django 4.1.7 on 2023-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shops_site_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
