# Generated by Django 4.1.7 on 2023-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shops_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='last_used_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last used date'),
        ),
    ]
