# Generated by Django 4.1.7 on 2023-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_configs_last_used_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='picked',
            field=models.BooleanField(default=False, verbose_name='Picked'),
        ),
    ]
