# Generated by Django 4.1.7 on 2023-04-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_proxies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxies',
            options={'verbose_name': 'Proxy', 'verbose_name_plural': 'Proxies (2400)'},
        ),
    ]
