# Generated by Django 4.1.7 on 2023-04-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_topsales_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsales',
            name='compare_at_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Compare_at_price'),
        ),
    ]
